/*1>name:-is generated by jvm using constructer of threadClass.setName("name") &getName();
 * 2>id:-we can't modify id of thread but can be read using getId(). jvm identified by using id
 * 3>priority:-range is 1 to 10. min-1,max-10,normal-5 these are static final variables of thread class.*/
package multiThread;
class Alpha extends Thread{
	public void run(){
		for(int n=65;n<=90;n++)
			System.out.println(getName()+":"+(char)n);
		System.out.println(getId());	
	}
}
public class ProperticeTest2 {

	public static void main(String[] args) {
		Alpha a1=new Alpha();
		Alpha a2=new Alpha();
		a1.setName("sri");
		a2.setName("patel");
		a1.start();
		a2.start();
	}

}
